In [2]:
import pandas as pd
import numpy as np

In [203]:
train=pd.read_csv('Train.csv')
test=pd.read_csv('Test.csv')

In [204]:
train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [205]:
test.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3

In [206]:
test.shape

(5681, 11)

In [207]:
train['type']='Train'
test['type']='Test'
test['Item_Outlet_Sales']=0
data=pd.merge(train,test,how='outer')
data.head()

F:\Anaconda\lib\site-packages\pandas\core\reshape\merge.py:938: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation
  'representation', UserWarning)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Train
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,Train
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Train
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,Train
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,Train

In [208]:
data.shape

(14204, 13)

In [209]:
data.isnull().sum()

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
type                            0
dtype: int64

In [210]:
data['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [211]:
data['Item_Fat_Content'].replace({'low fat':'Low Fat', 'LF': 'Low Fat', 'reg':'Regular'},inplace=True)

In [212]:
data['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [213]:

data['Item_Type'].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [214]:
data.groupby(['Outlet_Location_Type','Outlet_Type'])['Outlet_Size'].count()

Outlet_Location_Type  Outlet_Type
Tier 1                Grocery Store         880
                      Supermarket Type1    3100
Tier 2                Supermarket Type1    1550
Tier 3                Grocery Store           0
                      Supermarket Type1    1553
                      Supermarket Type2    1546
                      Supermarket Type3    1559
Name: Outlet_Size, dtype: int64

In [215]:
data.isnull().sum()

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
type                            0
dtype: int64

In [216]:
data[data['Item_Identifier']=='FDC37']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
23,FDC37,NaN,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876,Train
4652,FDC37,15.5,Low Fat,0.032846,Baking Goods,106.7938,OUT013,1987,High,Tier 3,Supermarket Type1,3215.8140,Train
6212,FDC37,15.5,Low Fat,0.032924,Baking Goods,107.2938,OUT049,1999,Medium,Tier 1,Supermarket Type1,2143.8760,Train
8594,FDC37,NaN,Low Fat,0.032714,Baking Goods,108.1938,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0000,Test
10482,FDC37,15.5,Low Fat,0.055023,Baking Goods,108.2938,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
10747,FDC37,15.5,Low Fat,0.032873,Baking Goods,106.2938,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
11046,FDC37,15.5,Low Fat,0.033007,Baking Goods,106.0938,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0000,Test
11254,FDC37,15.5,Low Fat,0.032867,Baking Goods,108.0938,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0000,Test
11712,FDC37,15.5,Low Fat,0.033059,Baking Goods,105.7938,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
13891,FDC37,15.5,Low Fat,0.032940,Baking Goods,107.0938,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test

In [217]:
pv=data.pivot_table(values='Item_Weight',index='Item_Identifier')
pv.head()

                 Item_Weight
Item_Identifier
DRA12                 11.600
DRA24                 19.350
DRA59                  8.270
DRB01                  7.390
DRB13                  6.115

In [218]:
def r(x):
    weight=x[0]
    identifier=x[1]
    if pd.isnull(weight):
        return pv['Item_Weight'][pv.index==identifier]
    else:
        return weight

In [219]:
data['Item_Weight']=data[['Item_Weight','Item_Identifier']].apply(r,axis=1).astype(float)

In [220]:
data.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
type                            0
dtype: int64

In [221]:
data[data['Outlet_Size'].isnull()]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,Train
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986,Train
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350,Train
25,NCD06,13.000,Low Fat,0.099887,Household,45.9060,OUT017,2007,NaN,Tier 2,Supermarket Type1,838.9080,Train
28,FDE51,5.925,Regular,0.161467,Dairy,45.5086,OUT010,1998,NaN,Tier 3,Grocery Store,178.4344,Train
30,FDV38,19.250,Low Fat,0.170349,Dairy,55.7956,OUT010,1998,NaN,Tier 3,Grocery Store,163.7868,Train
33,FDO23,17.850,Low Fat,0.000000,Breads,93.1436,OUT045,2002,NaN,Tier 2,Supermarket Type1,2174.5028,Train
45,FDM39,6.420,Low Fat,0.089499,Dairy,178.1002,OUT010,1998,NaN,Tier 3,Grocery Store,358.2004,Train
46,NCP05,19.600,Low Fat,0.000000,Health and Hygiene,153.3024,OUT045,2002,NaN,Tier 2,Supermarket Type1,2428.8384,Train
47,FDV49,10.000,Low Fat,0.025880,Canned,265.2226,OUT045,2002,NaN,Tier 2,Supermarket Type1,5815.0972,Train
53,FDA43,10.895,Low Fat,0.065042,Fruits and Vegetables,196.3794,OUT017,2007,NaN,Tier 2,Supermarket Type1,3121.2704,Train
54,NCP18,12.150,Low Fat,0.028760,Household,151.4708,OUT017,2007,NaN,Tier 2,Supermarket Type1,4815.0656,Train
56,NCX54,9.195,Low Fat,0.048157,Household,106.1622,OUT045,2002,NaN,Tier 2,Supermarket Type1,2117.2440,Train
61,FDV27,7.970,Regular,0.040071,Meat,87.3514,OUT045,2002,NaN,Tier 2,Supermarket Type1,1062.6168,Train
65,FDC46,17.700,Low Fat,0.195068,Snack Foods,185.4266,OUT010,1998,NaN,Tier 3,Grocery Store,184.4266,Train
67,FDZ03,13.650,Regular,0.078946,Dairy,186.0240,OUT045,2002,NaN,Tier 2,Supermarket Type1,1118.5440,Train
68,DRH37,17.600,Low Fat,0.041701,Soft Drinks,164.8526,OUT045,2002,NaN,Tier 2,Supermarket Type1,2302.3364,Train
72,FDH35,18.250,Low Fat,0.000000,Starchy Foods,164.7526,OUT045,2002,NaN,Tier 2,Supermarket Type1,4604.6728,Train
73,FDG02,7.855,Low Fat,0.011325,Canned,189.6188,OUT017,2007,NaN,Tier 2,Supermarket Type1,2285.0256,Train
78,FDL04,19.000,Low Fat,0.112557,Frozen Foods,104.9622,OUT017,2007,NaN,Tier 2,Supermarket Type1,1587.9330,Train
79,FDV25,5.905,Low Fat,0.000000,Canned,222.5456,OUT045,2002,NaN,Tier 2,Supermarket Type1,5305.0944,Train
85,FDG20,15.500,Regular,0.126399,Fruits and Vegetables,177.0028,OUT017,2007,NaN,Tier 2,Supermarket Type1,2479.4392,Train
90,FDW20,20.750,Low Fat,0.040421,Fruits and Vegetables,122.1730,OUT010,1998,NaN,Tier 3,Grocery Store,369.5190,Train
92,DRI25,19.600,Low Fat,0.033970,Soft Drinks,55.1614,OUT045,2002,NaN,Tier 2,Supermarket Type1,1381.5350,Train
100,FDT28,13.300,Low Fat,0.063695,Frozen Foods,151.0708,OUT045,2002,NaN,Tier 2,Supermarket Type1,1805.6496,Train
107,FDG12,6.635,Regular,0.000000,Baking Goods,121.3098,OUT045,2002,NaN,Tier 2,Supermarket Type1,2530.7058,Train
111,FDS52,8.890,Low Fat,0.005505,Frozen Foods,102.4016,OUT017,2007,NaN,Tier 2,Supermarket Type1,2732.4432,Train
114,FDV11,9.100,Regular,0.000000,Breads,173.2054,OUT045,2002,NaN,Tier 2,Supermarket Type1,3151.8972,Train
116,FDZ16,16.850,Regular,0.160760,Frozen Foods,192.4478,OUT017,2007,NaN,Tier 2,Supermarket Type1,4843.6950,Train
118,DRA12,11.600,Low Fat,0.041178,Soft Drinks,140.3154,OUT017,2007,NaN,Tier 2,Supermarket Type1,2552.6772,Train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14074,FDT60,12.000,Low Fat,0.126452,Baking Goods,123.6388,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
14075,FDK08,9.195,Regular,0.122553,Fruits and Vegetables,99.9016,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14083,FDT56,16.000,Regular,0.116246,Fruits and Vegetables,58.9246,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14094,FDI15,13.800,Low Fat,0.236595,Dairy,265.0884,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
14095,NCH43,8.420,Low Fat,0.118118,Household,216.9192,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
14097,NCG19,20.250,Low Fat,0.148770,Household,232.3616,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14099,FDB38,19.500,Regular,0.027501,Canned,157.9920,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14103,FDA23,9.800,Low Fat,0.078981,Baking Goods,100.1016,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
14107,FDG40,13.650,Low Fat,0.039905,Frozen Foods,34.4558,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14111,FDJ15,11.350,Regular,0.023370,Dairy,182.4608,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14117,FDM28,15.700,Low Fat,0.045460,Frozen Foods,178.2660,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14125,FDO21,11.600,Regular,0.009783,Snack Foods,224.8404,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14126,FDW39,6.690,Regular,0.000000,Meat,178.0370,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14130,DRF48,5.730,Low Fat,0.052094,Soft Drinks,185.4898,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14136,FDA16,6.695,Low Fat,0.034134,Frozen Foods,219.5456,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14141,FDU09,7.710,Regular,0.066974,Snack Foods,54.1956,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14143,FDB15,10.895,Low Fat,0.137088,Dairy,265.0568,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14147,FDP27,8.155,Low Fat,0.120126,Meat,191.6530,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14154,FDA03,18.500,Regular,0.045556,Dairy,147.1102,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14162,NCN26,10.850,Low Fat,0.028842,Household,116.9808,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14170,DRY23,9.395,Regular,0.109318,Soft Drinks,43.8112,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14172,DRH03,17.250,Low Fat,0.035135,Dairy,94.7120,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14173,FDC10,9.800,Regular,0.121982,Snack Foods,119.7098,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
14175,FDP32,6.650,Low Fat,0.087847,Fruits and Vegetables,126.7678,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14185,FDK22,9.800,Low Fat,0.026234,Snack Foods,214.3850,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14191,FDC44,15.600,Low Fat,0.288892,Fruits and Vegetables,115.1518,OUT010,1998,NaN,Tier 3,Grocery Store,0.0000,Test
14193,FDO03,10.395,Regular,0.037092,Meat,229.4352,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14201,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test
14202,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,0.0000,Test
14203,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,0.0000,Test

In [222]:
b=data.pivot_table(values='Outlet_Size',index='Outlet_Type',aggfunc=lambda x:x.mode())
b

                  Outlet_Size
Outlet_Type
Grocery Store           Small
Supermarket Type1       Small
Supermarket Type2      Medium
Supermarket Type3      Medium

In [223]:
def g(y):
    size=y[0]
    Type=y[1]
    if pd.isnull(size):
        return b['Outlet_Size'][b.index==Type][0]
    else:
        return size

In [224]:
data['Outlet_Size']=data[['Outlet_Size','Outlet_Type']].apply(g,axis=1)

In [225]:
data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
type                         0
dtype: int64

In [226]:
data[data['Outlet_Size']=='Small']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800,Train
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,Small,Tier 2,Supermarket Type1,1076.5986,Train
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,Small,Tier 2,Supermarket Type1,4710.5350,Train
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530,Train
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076,Train
15,FDP49,9.000,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192,Train
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1,2748.4224,Train
22,NCB30,14.600,Low Fat,0.025698,Household,196.5084,OUT035,2004,Small,Tier 2,Supermarket Type1,1587.2672,Train
23,FDC37,15.500,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876,Train
24,FDR28,13.850,Regular,0.025896,Frozen Foods,165.0210,OUT046,1997,Small,Tier 1,Supermarket Type1,4078.0250,Train
25,NCD06,13.000,Low Fat,0.099887,Household,45.9060,OUT017,2007,Small,Tier 2,Supermarket Type1,838.9080,Train
26,FDV10,7.645,Regular,0.066693,Snack Foods,42.3112,OUT035,2004,Small,Tier 2,Supermarket Type1,1065.2800,Train
28,FDE51,5.925,Regular,0.161467,Dairy,45.5086,OUT010,1998,Small,Tier 3,Grocery Store,178.4344,Train
29,FDC14,14.500,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362,Train
30,FDV38,19.250,Low Fat,0.170349,Dairy,55.7956,OUT010,1998,Small,Tier 3,Grocery Store,163.7868,Train
33,FDO23,17.850,Low Fat,0.000000,Breads,93.1436,OUT045,2002,Small,Tier 2,Supermarket Type1,2174.5028,Train
34,DRH01,17.500,Low Fat,0.097904,Soft Drinks,174.8738,OUT046,1997,Small,Tier 1,Supermarket Type1,2085.2856,Train
40,FDU02,13.350,Low Fat,0.102512,Dairy,230.6352,OUT046,1997,Small,Tier 1,Supermarket Type1,3435.5280,Train
45,FDM39,6.420,Low Fat,0.089499,Dairy,178.1002,OUT010,1998,Small,Tier 3,Grocery Store,358.2004,Train
46,NCP05,19.600,Low Fat,0.000000,Health and Hygiene,153.3024,OUT045,2002,Small,Tier 2,Supermarket Type1,2428.8384,Train
47,FDV49,10.000,Low Fat,0.025880,Canned,265.2226,OUT045,2002,Small,Tier 2,Supermarket Type1,5815.0972,Train
48,FDL12,15.850,Regular,0.121633,Baking Goods,60.6220,OUT046,1997,Small,Tier 1,Supermarket Type1,2576.6460,Train
49,FDS02,10.195,Regular,0.255395,Dairy,196.8794,OUT019,1985,Small,Tier 1,Grocery Store,780.3176,Train
50,NCL17,7.390,Low Fat,0.067780,Health and Hygiene,143.8812,OUT046,1997,Small,Tier 1,Supermarket Type1,3134.5864,Train
53,FDA43,10.895,Low Fat,0.065042,Fruits and Vegetables,196.3794,OUT017,2007,Small,Tier 2,Supermarket Type1,3121.2704,Train
54,NCP18,12.150,Low Fat,0.028760,Household,151.4708,OUT017,2007,Small,Tier 2,Supermarket Type1,4815.0656,Train
56,NCX54,9.195,Low Fat,0.048157,Household,106.1622,OUT045,2002,Small,Tier 2,Supermarket Type1,2117.2440,Train
58,FDY21,15.100,Low Fat,0.173481,Snack Foods,194.5110,OUT046,1997,Small,Tier 1,Supermarket Type1,4910.2750,Train
59,FDI26,5.940,Low Fat,0.061082,Canned,180.0344,OUT019,1985,Small,Tier 1,Grocery Store,892.1720,Train
61,FDV27,7.970,Regular,0.040071,Meat,87.3514,OUT045,2002,Small,Tier 2,Supermarket Type1,1062.6168,Train
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14133,FDP23,6.710,Low Fat,0.035587,Breads,219.5166,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14136,FDA16,6.695,Low Fat,0.034134,Frozen Foods,219.5456,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14137,FDN20,19.350,Low Fat,0.000000,Fruits and Vegetables,167.1474,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0000,Test
14141,FDU09,7.710,Regular,0.066974,Snack Foods,54.1956,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14142,FDW01,14.500,Low Fat,0.064061,Canned,154.0682,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14143,FDB15,10.895,Low Fat,0.137088,Dairy,265.0568,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test
14147,FDP27,8.155,Low Fat,0.120126,Meat,191.6530,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14152,NCV30,20.200,Low Fat,0.065920,Household,61.2510,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0000,Test
14154,FDA03,18.500,Regular,0.045556,Dairy,147.1102,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test
14158,NCS41,12.850,Low Fat,0.000000,Health and Hygiene,184.2608,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14160,DRK59,8.895,Low Fat,0.075450,Hard Drinks,233.2616,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14161,NCG18,15.300,Low Fat,0.022978,Household,103.1332,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14162,NCN26,10.850,Low Fat,0.028842,Household,116.9808,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14166,FDQ19,7.350,Regular,0.000000,Fruits and Vegetables,244.3512,OUT019,1985,Small,Tier 1,Grocery Store,0.0000,Test
14170,DRY23,9.395,Regular,0.109318,Soft Drinks,43.8112,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test
14172,DRH03,17.250,Low Fat,0.035135,Dairy,94.7120,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test
14173,FDC10,9.800,Regular,0.121982,Snack Foods,119.7098,OUT010,1998,Small,Tier 3,Grocery Store,0.0000,Test
14175,FDP32,6.650,Low Fat,0.087847,Fruits and Vegetables,126.7678,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test
14176,FDO31,6.760,Regular,0.028977,Fruits and Vegetables,80.2960,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0000,Test
14180,FDU55,16.200,Low Fat,0.035911,Fruits and Vegetables,261.3278,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14185,FDK22,9.800,Low Fat,0.026234,Snack Foods,214.3850,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14189,FDF34,9.300,Regular,0.014019,Snack Foods,196.9084,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14190,FDZ22,9.395,Low Fat,0.045270,Snack Foods,82.1250,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14191,FDC44,15.600,Low Fat,0.288892,Fruits and Vegetables,115.1518,OUT010,1998,Small,Tier 3,Grocery Store,0.0000,Test
14193,FDO03,10.395,Regular,0.037092,Meat,229.4352,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14197,DRL35,15.700,Low Fat,0.030704,Hard Drinks,43.2770,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14199,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0000,Test
14201,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test
14202,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0000,Test
14203,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0000,Test

In [227]:
pd.DataFrame(data.groupby('Outlet_Identifier')['Item_Outlet_Sales'].sum())

                   Item_Outlet_Sales
Outlet_Identifier
OUT010                  1.883402e+05
OUT013                  2.142664e+06
OUT017                  2.167465e+06
OUT018                  1.851823e+06
OUT019                  1.796941e+05
OUT027                  3.453926e+06
OUT035                  2.268123e+06
OUT045                  2.036725e+06
OUT046                  2.118395e+06
OUT049                  2.183970e+06

In [228]:
data[data['Item_Identifier']=='FDP10']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
7,FDP10,19.0,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636,Train
585,FDP10,19.0,Low Fat,0.128066,Snack Foods,104.3622,OUT035,2004,Small,Tier 2,Supermarket Type1,1905.5196,Train
2623,FDP10,19.0,Low Fat,0.128815,Snack Foods,107.6622,OUT017,2007,Small,Tier 2,Supermarket Type1,1164.4842,Train
3382,FDP10,19.0,Low Fat,0.128289,Snack Foods,104.9622,OUT049,1999,Medium,Tier 1,Supermarket Type1,1164.4842,Train
4585,FDP10,19.0,Low Fat,0.128090,Snack Foods,107.0622,OUT046,1997,Small,Tier 1,Supermarket Type1,1376.2086,Train
6087,FDP10,19.0,Low Fat,0.128350,Snack Foods,106.5622,OUT045,2002,Small,Tier 2,Supermarket Type1,1482.0708,Train
7883,FDP10,19.0,Low Fat,0.127984,Snack Foods,107.6622,OUT013,1987,High,Tier 3,Supermarket Type1,1270.3464,Train
11896,FDP10,19.0,Low Fat,0.128612,Snack Foods,104.1622,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0000,Test
12371,FDP10,19.0,Low Fat,0.214397,Snack Foods,105.8622,OUT010,1998,Small,Tier 3,Grocery Store,0.0000,Test
13327,FDP10,19.0,Low Fat,0.224269,Snack Foods,104.4622,OUT019,1985,Small,Tier 1,Grocery Store,0.0000,Test

In [229]:
data.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Train
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,Train
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Train
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800,Train
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,Train
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088,Train
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528,Train
7,FDP10,19.000,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636,Train
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,Small,Tier 2,Supermarket Type1,1076.5986,Train
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,Small,Tier 2,Supermarket Type1,4710.5350,Train
10,FDY07,11.800,Low Fat,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1,1516.0266,Train
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530,Train
12,FDX32,15.100,Regular,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1,1589.2646,Train
13,FDS46,17.600,Regular,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1,2145.2076,Train
14,FDF32,16.350,Low Fat,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1,1977.4260,Train
15,FDP49,9.000,Regular,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192,Train
16,NCB42,11.800,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888,Train
17,FDP49,9.000,Regular,0.069196,Breakfast,54.3614,OUT049,1999,Medium,Tier 1,Supermarket Type1,718.3982,Train
18,DRI11,8.260,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680,Train
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1,2748.4224,Train

In [230]:
data.pivot_table(values='Item_Outlet_Sales',index='Outlet_Type')

                   Item_Outlet_Sales
Outlet_Type
Grocery Store             203.897100
Supermarket Type1        1389.858216
Supermarket Type2        1197.815543
Supermarket Type3        2215.475338

In [231]:
item_visi=data.pivot_table(values='Item_Visibility',index='Item_Identifier')
item_visi.head()

                 Item_Visibility
Item_Identifier
DRA12                   0.034938
DRA24                   0.045646
DRA59                   0.133384
DRB01                   0.079736
DRB13                   0.006799

In [232]:
(data.loc[(data['Item_Visibility']==0),'Item_Visibility']).count()

879

In [233]:
data.Item_Visibility.mean()

0.06595278007399345

In [234]:
def g(x):
    visibility=x[0]
    identifier=x[1]
    if visibility == 0:
        return item_visi['Item_Visibility'][item_visi.index==identifier]
    else:
        return visibility

In [235]:
data['Item_Visibility']=data[['Item_Visibility','Item_Identifier']].apply(g,axis=1).astype(float)

In [236]:
data[data['Item_Visibility']==0]

Empty DataFrame
Columns: [Item_Identifier, Item_Weight, Item_Fat_Content, Item_Visibility, Item_Type, Item_MRP, Outlet_Identifier, Outlet_Establishment_Year, Outlet_Size, Outlet_Location_Type, Outlet_Type, Item_Outlet_Sales, type]
Index: []

In [241]:
data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
type                         0
dtype: int64

In [243]:
data['Item_Type'].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [244]:
data[data['Item_Outlet_Sales']==0]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
8523,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
8524,FDW14,8.300,Regular,0.038428,Dairy,87.3198,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
8525,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,Small,Tier 3,Grocery Store,0.0,Test
8526,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
8527,FDY38,13.600,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
8528,FDH56,9.800,Regular,0.063817,Fruits and Vegetables,117.1492,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
8529,FDL48,19.350,Regular,0.082602,Baking Goods,50.1034,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0,Test
8530,FDC48,9.195,Low Fat,0.015782,Baking Goods,81.0592,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
8531,FDN33,6.305,Regular,0.123365,Snack Foods,95.7436,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0,Test
8532,FDA36,5.985,Low Fat,0.005698,Baking Goods,186.8924,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
8533,FDT44,16.600,Low Fat,0.103569,Fruits and Vegetables,118.3466,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
8534,FDQ56,6.590,Low Fat,0.105811,Fruits and Vegetables,85.3908,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0,Test
8535,NCC54,17.750,Low Fat,0.171079,Health and Hygiene,240.4196,OUT019,1985,Small,Tier 1,Grocery Store,0.0,Test
8536,FDU11,4.785,Low Fat,0.092738,Breads,122.3098,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
8537,DRL59,16.750,Low Fat,0.021206,Hard Drinks,52.0298,OUT013,1987,High,Tier 3,Supermarket Type1,0.0,Test
8538,FDM24,6.135,Regular,0.079451,Baking Goods,151.6366,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
8539,FDI57,19.850,Low Fat,0.054135,Seafood,198.7768,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0,Test
8540,DRC12,17.850,Low Fat,0.037981,Soft Drinks,192.2188,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0,Test
8541,NCM42,6.130,Low Fat,0.028184,Household,109.6912,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
8542,FDA46,13.600,Low Fat,0.196898,Snack Foods,193.7136,OUT010,1998,Small,Tier 3,Grocery Store,0.0,Test
8543,FDA31,7.100,Low Fat,0.109920,Fruits and Vegetables,175.0080,OUT013,1987,High,Tier 3,Supermarket Type1,0.0,Test
8544,NCJ31,19.200,Low Fat,0.182619,Others,239.9196,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0,Test
8545,FDG52,13.650,Low Fat,0.065631,Frozen Foods,47.7402,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
8546,NCL19,15.350,Low Fat,0.027447,Others,142.3470,OUT019,1985,Small,Tier 1,Grocery Store,0.0,Test
8547,FDS10,19.200,Low Fat,0.035179,Snack Foods,180.7318,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0,Test
8548,FDX22,6.785,Regular,0.038455,Snack Foods,209.4928,OUT010,1998,Small,Tier 3,Grocery Store,0.0,Test
8549,NCF19,13.000,Low Fat,0.035102,Household,47.6034,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0,Test
8550,NCE06,5.825,Low Fat,0.091485,Household,161.3894,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
8551,DRC27,13.800,Low Fat,0.058102,Dairy,244.6802,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
8552,FDE21,12.800,Low Fat,0.022940,Fruits and Vegetables,116.5492,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14174,FDD23,9.500,Regular,0.048645,Starchy Foods,186.1898,OUT013,1987,High,Tier 3,Supermarket Type1,0.0,Test
14175,FDP32,6.650,Low Fat,0.087847,Fruits and Vegetables,126.7678,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0,Test
14176,FDO31,6.760,Regular,0.028977,Fruits and Vegetables,80.2960,OUT035,2004,Small,Tier 2,Supermarket Type1,0.0,Test
14177,FDQ57,7.275,Low Fat,0.024077,Snack Foods,144.5760,OUT013,1987,High,Tier 3,Supermarket Type1,0.0,Test
14178,FDX32,15.100,Regular,0.099375,Fruits and Vegetables,143.6786,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
14179,FDC39,7.405,Low Fat,0.158425,Dairy,207.8296,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
14180,FDU55,16.200,Low Fat,0.035911,Fruits and Vegetables,261.3278,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
14181,FDL45,15.600,Low Fat,0.037656,Snack Foods,123.4704,OUT013,1987,High,Tier 3,Supermarket Type1,0.0,Test
14182,DRK37,5.000,Low Fat,0.044073,Soft Drinks,188.8530,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
14183,FDK22,9.800,Low Fat,0.026065,Snack Foods,215.3850,OUT013,1987,High,Tier 3,Supermarket Type1,0.0,Test
14184,DRG37,16.200,Low Fat,0.020225,Soft Drinks,155.7972,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
14185,FDK22,9.800,Low Fat,0.026234,Snack Foods,214.3850,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
14186,DRH36,16.200,Low Fat,0.033516,Soft Drinks,72.8696,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0,Test
14187,DRC36,13.000,Regular,0.045168,Soft Drinks,173.4054,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0,Test
14188,DRE03,19.600,Low Fat,0.024110,Dairy,46.0718,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
14189,FDF34,9.300,Regular,0.014019,Snack Foods,196.9084,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
14190,FDZ22,9.395,Low Fat,0.045270,Snack Foods,82.1250,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
14191,FDC44,15.600,Low Fat,0.288892,Fruits and Vegetables,115.1518,OUT010,1998,Small,Tier 3,Grocery Store,0.0,Test
14192,FDN31,11.500,Low Fat,0.072529,Fruits and Vegetables,188.0530,OUT027,1985,Medium,Tier 3,Supermarket Type3,0.0,Test
14193,FDO03,10.395,Regular,0.037092,Meat,229.4352,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
14194,FDA01,15.000,Regular,0.054463,Canned,59.5904,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
14195,NCH42,6.860,Low Fat,0.036594,Household,231.1010,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
14196,FDF46,7.070,Low Fat,0.094053,Snack Foods,116.0834,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0,Test
14197,DRL35,15.700,Low Fat,0.030704,Hard Drinks,43.2770,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
14198,FDW46,13.000,Regular,0.070411,Snack Foods,63.4484,OUT049,1999,Medium,Tier 1,Supermarket Type1,0.0,Test
14199,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,0.0,Test
14200,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,0.0,Test
14201,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0,Test
14202,FDJ26,15.300,Regular,0.088380,Canned,214.6218,OUT017,2007,Small,Tier 2,Supermarket Type1,0.0,Test
14203,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,Small,Tier 2,Supermarket Type1,0.0,Test

In [245]:
data['Item_Outlet_Sales'].median()

559.2719999999999

In [246]:
data[data['Item_Outlet_Sales']==1621.8888]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
16,NCB42,11.8,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888,Train
3788,FDH56,9.8,Regular,0.064077,Fruits and Vegetables,116.7492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888,Train
3910,NCX05,15.2,Low Fat,0.096592,Health and Hygiene,117.4492,OUT027,1985,Medium,Tier 3,Supermarket Type3,1621.8888,Train
5005,NCA18,10.1,Low Fat,0.056078,Household,117.8492,OUT046,1997,Small,Tier 1,Supermarket Type1,1621.8888,Train

In [247]:
from sklearn.preprocessing import LabelEncoder

In [248]:
le=LabelEncoder()

In [249]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Train
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,Train
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Train
3,FDX07,19.20,Regular,0.017834,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800,Train
4,NCD19,8.93,Low Fat,0.009780,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,Train

In [251]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Train
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,Train
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Train
3,FDX07,19.20,Regular,0.017834,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store,732.3800,Train
4,NCD19,8.93,Low Fat,0.009780,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,Train

In [253]:
data['Item_Identifier'].unique()

array(['FDA15', 'DRC01', 'FDN15', ..., 'NCF55', 'NCW30', 'NCW05'],
      dtype=object)

In [255]:
def u(c):
    return(c[-2:])

In [256]:
data['Item_Identifier']=data['Item_Identifier'].apply(u)

In [257]:
data['Outlet_Identifier']=data['Outlet_Identifier'].apply(u)

In [258]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
0,15,9.30,Low Fat,0.016047,Dairy,249.8092,49,1999,Medium,Tier 1,Supermarket Type1,3735.1380,Train
1,01,5.92,Regular,0.019278,Soft Drinks,48.2692,18,2009,Medium,Tier 3,Supermarket Type2,443.4228,Train
2,15,17.50,Low Fat,0.016760,Meat,141.6180,49,1999,Medium,Tier 1,Supermarket Type1,2097.2700,Train
3,07,19.20,Regular,0.017834,Fruits and Vegetables,182.0950,10,1998,Small,Tier 3,Grocery Store,732.3800,Train
4,19,8.93,Low Fat,0.009780,Household,53.8614,13,1987,High,Tier 3,Supermarket Type1,994.7052,Train

In [259]:
data['Item_Fat_Content']=le.fit_transform(data['Item_Fat_Content'])
data['Item_Type']=le.fit_transform(data['Item_Type'])
data['Outlet_Size']=le.fit_transform(data['Outlet_Size'])
data['Outlet_Location_Type']=le.fit_transform(data['Outlet_Location_Type'])
data['Outlet_Type']=le.fit_transform(data['Outlet_Type'])

In [260]:
data.to_csv('Cleaned file.csv',index=False)

In [280]:
m=pd.read_csv('Cleaned file.csv')
m.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type
0,15,9.30,0,0.016047,4,249.8092,49,1999,1,0,1,3735.1380,Train
1,1,5.92,1,0.019278,14,48.2692,18,2009,1,2,2,443.4228,Train
2,15,17.50,0,0.016760,10,141.6180,49,1999,1,0,1,2097.2700,Train
3,7,19.20,1,0.017834,6,182.0950,10,1998,2,2,0,732.3800,Train
4,19,8.93,0,0.009780,9,53.8614,13,1987,0,2,1,994.7052,Train

In [281]:
M1=pd.get_dummies(m,drop_first=True)
M1.tail()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,type_Train
14199,58,10.5,1,0.013496,13,141.3154,46,1997,2,0,1,0.0,0
14200,47,7.6,1,0.142991,15,169.1448,18,2009,1,2,2,0.0,0
14201,17,10.0,0,0.073529,8,118.7440,45,2002,2,1,1,0.0,0
14202,26,15.3,1,0.088380,3,214.6218,17,2007,2,1,1,0.0,0
14203,37,9.5,1,0.104720,3,79.7960,45,2002,2,1,1,0.0,0

In [282]:
train=M1[M1['type_Train']==1]
test=M1[M1['type_Train']==0]

In [283]:
train.shape

(8523, 13)

In [284]:
test.shape

(5681, 13)

In [285]:
test.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales', 'type_Train'],
      dtype='object')

In [286]:
train.drop('type_Train',inplace=True,axis=1)
test.drop('type_Train',inplace=True,axis=1)

F:\Anaconda\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [287]:
train.shape

(8523, 12)

In [288]:
test.shape

(5681, 12)

In [289]:
m.shape

(14204, 13)

In [299]:
test.drop('Item_Outlet_Sales',axis=1,inplace=True)
test.head()

F:\Anaconda\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
8523,58,20.750,0,0.007565,13,107.8622,49,1999,1,0,1
8524,14,8.300,1,0.038428,4,87.3198,17,2007,2,1,1
8525,55,14.600,0,0.099575,11,241.7538,10,1998,2,2,0
8526,58,7.315,0,0.015388,13,155.0340,17,2007,2,1,1
8527,38,13.600,1,0.118599,4,234.2300,27,1985,1,2,3

In [300]:
x_train=train.drop('Item_Outlet_Sales',axis=1)
x_test=test
y_train=train['Item_Outlet_Sales']

In [301]:
from sklearn.linear_model import LinearRegression

In [302]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [303]:
x_test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
8523,58,20.750,0,0.007565,13,107.8622,49,1999,1,0,1
8524,14,8.300,1,0.038428,4,87.3198,17,2007,2,1,1
8525,55,14.600,0,0.099575,11,241.7538,10,1998,2,2,0
8526,58,7.315,0,0.015388,13,155.0340,17,2007,2,1,1
8527,38,13.600,1,0.118599,4,234.2300,27,1985,1,2,3
8528,56,9.800,1,0.063817,6,117.1492,46,1997,2,0,1
8529,48,19.350,1,0.082602,0,50.1034,18,2009,1,2,2
8530,48,9.195,0,0.015782,0,81.0592,27,1985,1,2,3
8531,33,6.305,1,0.123365,13,95.7436,45,2002,2,1,1
8532,36,5.985,0,0.005698,0,186.8924,17,2007,2,1,1
8533,44,16.600,0,0.103569,6,118.3466,17,2007,2,1,1
8534,56,6.590,0,0.105811,6,85.3908,45,2002,2,1,1
8535,54,17.750,0,0.171079,8,240.4196,19,1985,2,0,0
8536,11,4.785,0,0.092738,1,122.3098,49,1999,1,0,1
8537,59,16.750,0,0.021206,7,52.0298,13,1987,0,2,1
8538,24,6.135,1,0.079451,0,151.6366,49,1999,1,0,1
8539,57,19.850,0,0.054135,12,198.7768,45,2002,2,1,1
8540,12,17.850,0,0.037981,14,192.2188,18,2009,1,2,2
8541,42,6.130,0,0.028184,9,109.6912,27,1985,1,2,3
8542,46,13.600,0,0.196898,13,193.7136,10,1998,2,2,0
8543,31,7.100,0,0.109920,6,175.0080,13,1987,0,2,1
8544,31,19.200,0,0.182619,11,239.9196,35,2004,2,1,1
8545,52,13.650,0,0.065631,5,47.7402,46,1997,2,0,1
8546,19,15.350,0,0.027447,11,142.3470,19,1985,2,0,0
8547,10,19.200,0,0.035179,13,180.7318,35,2004,2,1,1
8548,22,6.785,1,0.038455,13,209.4928,10,1998,2,2,0
8549,19,13.000,0,0.035102,9,47.6034,35,2004,2,1,1
8550,6,5.825,0,0.091485,9,161.3894,46,1997,2,0,1
8551,27,13.800,0,0.058102,4,244.6802,46,1997,2,0,1
8552,21,12.800,0,0.022940,6,116.5492,35,2004,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...
14174,23,9.500,1,0.048645,15,186.1898,13,1987,0,2,1
14175,32,6.650,0,0.087847,6,126.7678,45,2002,2,1,1
14176,31,6.760,1,0.028977,6,80.2960,35,2004,2,1,1
14177,57,7.275,0,0.024077,13,144.5760,13,1987,0,2,1
14178,32,15.100,1,0.099375,6,143.6786,27,1985,1,2,3
14179,39,7.405,0,0.158425,4,207.8296,27,1985,1,2,3
14180,55,16.200,0,0.035911,6,261.3278,46,1997,2,0,1
14181,45,15.600,0,0.037656,13,123.4704,13,1987,0,2,1
14182,37,5.000,0,0.044073,14,188.8530,49,1999,1,0,1
14183,22,9.800,0,0.026065,13,215.3850,13,1987,0,2,1
14184,37,16.200,0,0.020225,14,155.7972,27,1985,1,2,3
14185,22,9.800,0,0.026234,13,214.3850,17,2007,2,1,1
14186,36,16.200,0,0.033516,14,72.8696,18,2009,1,2,2
14187,36,13.000,1,0.045168,14,173.4054,18,2009,1,2,2
14188,3,19.600,0,0.024110,4,46.0718,27,1985,1,2,3
14189,34,9.300,1,0.014019,13,196.9084,46,1997,2,0,1
14190,22,9.395,0,0.045270,13,82.1250,46,1997,2,0,1
14191,44,15.600,0,0.288892,6,115.1518,10,1998,2,2,0
14192,31,11.500,0,0.072529,6,188.0530,27,1985,1,2,3
14193,3,10.395,1,0.037092,10,229.4352,17,2007,2,1,1
14194,1,15.000,1,0.054463,3,59.5904,49,1999,1,0,1
14195,42,6.860,0,0.036594,9,231.1010,49,1999,1,0,1
14196,46,7.070,0,0.094053,13,116.0834,18,2009,1,2,2
14197,35,15.700,0,0.030704,7,43.2770,46,1997,2,0,1
14198,46,13.000,1,0.070411,13,63.4484,49,1999,1,0,1
14199,58,10.500,1,0.013496,13,141.3154,46,1997,2,0,1
14200,47,7.600,1,0.142991,15,169.1448,18,2009,1,2,2
14201,17,10.000,0,0.073529,8,118.7440,45,2002,2,1,1
14202,26,15.300,1,0.088380,3,214.6218,17,2007,2,1,1
14203,37,9.500,1,0.104720,3,79.7960,45,2002,2,1,1

In [304]:
h=lr.predict(x_test)
h

array([2094.92405448,  914.06204463, 2353.85009965, ..., 1813.99547761,
       2862.16544009, 1296.10925355])

In [316]:
from sklearn.metrics import r2_score

In [315]:
# rmse=np.sqrt(mean_squared_error(h,x_test))
# rmse

ValueError: y_true and y_pred have different number of output (1!=11)

In [320]:
r2_score(x_test,y_train)

ValueError: Found input variables with inconsistent numbers of samples: [5681, 8523]

In [321]:
lr_accuracy = round(lr.score(x_train,y_train) * 100,2)
lr_accuracy

51.04

In [323]:
linear_submission = pd.DataFrame({
    'Item_Identifier':test['Item_Identifier'],
    'Outlet_Identifier':test['Outlet_Identifier'],
    'Item_Outlet_Sales': h
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [324]:
linear_submission.to_csv('Lr_sub.csv',index=False)

In [325]:
from sklearn.tree import DecisionTreeRegressor

In [326]:
tree = DecisionTreeRegressor(max_depth=15,min_samples_leaf=100)

In [327]:
tree.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=15, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=100,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [328]:
tp=tree.predict(x_test)

In [330]:
tree_accuracy = round(tree.score(x_train,y_train),2)
tree_accuracy

0.62

In [331]:
tree_submission = pd.DataFrame({
    'Item_Identifier':test['Item_Identifier'],
    'Outlet_Identifier':test['Outlet_Identifier'],
    'Item_Outlet_Sales': tp
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [332]:
tree_submission.to_csv('Tree_algo.csv',index=False)

In [333]:
from sklearn.ensemble import RandomForestRegressor

In [334]:
rf = RandomForestRegressor(n_estimators=400,max_depth=6, min_samples_leaf=100,n_jobs=4)

In [335]:
rf.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=6,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=100, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=400, n_jobs=4,
                      oob_score=False, random_state=None, verbose=0,
                      warm_start=False)

In [336]:
rfp=rf.predict(x_test)

In [338]:
rf_accuracy = round(rf.score(x_train,y_train),2)
rf_accuracy

0.61

In [340]:
rf_submission = pd.DataFrame({
    'Item_Identifier':test['Item_Identifier'],
    'Outlet_Identifier':test['Outlet_Identifier'],
    'Item_Outlet_Sales': rfp
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [341]:
rf_submission.to_csv('Rf.csv',index=False)